kind: pipeline
type: docker
name: default

steps:
- name: test
  image: kameshsampath/drone-java-maven-plugin:v1.0.3
  pull: if-not-exists
  settings:
    maven_mirror_url: http://nexus:8081/repository/maven-public/
    goals:
    - -B 
    - clean 
    - test

- name: build
  image: kameshsampath/drone-java-maven-plugin:v1.0.3
  pull: if-not-exists
  settings:
    maven_mirror_url: http://nexus:8081/repository/maven-public/
    goals:
    - -B 
    - clean 
    - install
    - -DskipTests

- name: push
  image: thegeeklab/drone-docker-buildx
  privileged: true
  pull: if-not-exists
  settings:
    platforms:
      - linux/amd64
      - linux/arm64
    context: .

services:
  - name: postgresql
    image: postgres:14.4-alpine
  # If you are using mysql/mariadb, uncomment this
  # - name: mariadb
  #   image: mariadb