version: "3.7"
services:
  #https://github.com/kameshsampath/podman-pgsql/tree/master/pgsql12-primary-centos8
  postgresql:
    image: postgres:13.15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: demo
      POSTGRES_DB: fruitsdb
