version: "3.7"
services:
  postgresql:
    image: postgres:14.3-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
  # mariadb:
  #   image: mariadb
  #   ports:
  #     - "3306:3306"
  #   env_file:
  #     - .env
  fruits-api:
    image: "${PLUGIN_REGISTRY}/${PLUGIN_REPO}:${PLUGIN_TAG}"
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgresql
    #  - mariadb
networks:
  fruits-app: