version: "3.7"
services:
  fruits-api:
    image: "${PLUGIN_REGISTRY}/${PLUGIN_REPO}:${PLUGIN_TAG}"
    ports:
      - "8080:8080"
  postgresql:
    image: postgres:14.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: demo
      POSTGRES_DB: fruitsdb
networks:
  fruits-app: