FROM registry.access.redhat.com/ubi8/openjdk-11

LABEL org.opencontainers.image.source=https://github.com/kameshsampath/fruits-api

COPY target/quarkus-app/lib/ /deployments/lib/
COPY target/quarkus-app/*.jar /deployments/
COPY target/quarkus-app/app/ /deployments/app/
COPY target/quarkus-app/quarkus/ /deployments/quarkus/
