FROM gcr.io/distroless/java17-debian11	

LABEL org.opencontainers.image.source=https://github.com/kameshsampath/fruits-api

WORKDIR /app

COPY target/quarkus-app/lib/ /app/lib/
COPY target/quarkus-app/quarkus-run.jar /app/
COPY target/quarkus-app/app/ /app/app/
COPY target/quarkus-app/quarkus/ /app/quarkus/

CMD ["quarkus-run.jar"]