apiVersion: portal.gloo.solo.io/v1beta1
kind: Group
metadata:
  name: users
spec:
  displayName: corporate users
  accessLevel:
    portals:
    - name: fruits-portal
      namespace: default
  oidcGroup:
    groupName: users
